In [30]:
import pandas as pd
import numpy as np
from datetime import datetime

# Fix datatime format

In [27]:
df = pd.read_csv('synthetic_data_v0.csv')
df.head(20)

,Unnamed: 0,Location,Role,VendorID,InvoiceValue,Resource,StartTimestamp,EndTimestamp,CaseId,ActivityName
0,0,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,28-07-2021 15:11,28-07-2021 17:09,140,Invoice Entry
1,1,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,28-07-2021 17:09,28-07-2021 18:38,140,Check Customer Payment
2,2,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,28-07-2021 17:09,28-07-2021 18:38,140,Credit Memo Entry
3,3,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,29-07-2021 11:33,29-07-2021 11:33,140,Refund Customer
4,4,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,29-07-2021 17:48,29-07-2021 18:17,140,Re-issuing the invoice
5,5,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,26-07-2021 12:19,26-07-2021 13:23,141,Invoice Entry
6,6,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,26-07-2021 13:35,26-07-2021 14:33,141,Confirm Payment Received
7,7,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,26-07-2021 14:28,26-07-2021 16:20,141,Refund With Special Voucher
8,8,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,26-07-2021 17:35,26-07-2021 18:21,141,Complete the Customer Memo
9,9,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,26-07-2021 17:35,26-07-2021 19:33,141,Reject Invoice
10,10,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,27-07-2021 09:33,27-07-2021 10:08,141,Refund With Standard Voucher
11,11,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,27-07-2021 10:17,27-07-2021 13:47,141,Complete the Customer Memo
12,12,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,27-07-2021 10:35,27-07-2021 10:17,141,Reject Invoice
13,13,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,27-07-2021 16:05,27-07-2021 19:43,141,Refund With Special Voucher
14,14,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,27-07-2021 16:39,27-07-2021 19:43,141,Complete the Customer Memo
15,15,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,28-07-2021 12:57,28-07-2021 13:39,141,Approve Invoice
16,16,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,28-07-2021 12:57,28-07-2021 14:01,141,Credit Memo Creation
17,17,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,28-07-2021 12:57,28-07-2021 14:01,141,Fill Credit Memo
18,18,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,28-07-2021 15:24,28-07-2021 15:24,141,Re-issuing the invoice
19,19,"Seattle, USA",Invoice Processor,Vendor4,443.774000,Riley,29-07-2021 14:43,29-07-2021 15:27,142,Invoice Entry

In [19]:
date_format = '%d-%m-%Y %H:%M'
df.loc[:,'StartTimestamp'] = df.loc[:,'StartTimestamp'].apply(lambda x: datetime.strptime(x, date_format))
df.loc[:,'EndTimestamp'] = df.loc[:,'EndTimestamp'].apply(lambda x: datetime.strptime(x, date_format))

In [24]:
df.to_csv('synthetic_data_v0a.csv')

# Analyze Activity order
## Sythetic data file

In [70]:
df2 = pd.read_csv('synthetic_data_v0a.csv')
df2 = df2.iloc[:,2:]
df2.head(5)

,Location,Role,VendorID,InvoiceValue,Resource,StartTimestamp,EndTimestamp,CaseId,ActivityName
0,"Seattle, USA",Invoice Processor,Vendor1,1535.634,Riley,2021-07-28 15:11:00,2021-07-28 17:09:00,140,Invoice Entry
1,"Seattle, USA",Invoice Processor,Vendor1,1535.634,Riley,2021-07-28 17:09:00,2021-07-28 18:38:00,140,Check Customer Payment
2,"Seattle, USA",Invoice Processor,Vendor1,1535.634,Riley,2021-07-28 17:09:00,2021-07-28 18:38:00,140,Credit Memo Entry
3,"Seattle, USA",Invoice Processor,Vendor1,1535.634,Riley,2021-07-29 11:33:00,2021-07-29 11:33:00,140,Refund Customer
4,"Seattle, USA",Invoice Processor,Vendor1,1535.634,Riley,2021-07-29 17:48:00,2021-07-29 18:17:00,140,Re-issuing the invoice

In [107]:
len(df2.CaseId.unique())

500

In [71]:
df2['ActivityName'].unique()

array(['Invoice Entry', 'Check Customer Payment', 'Credit Memo Entry',
       'Refund Customer', 'Re-issuing the invoice',
       'Confirm Payment Received', 'Refund With Special Voucher',
       'Complete the Customer Memo', 'Reject Invoice',
       'Refund With Standard Voucher', 'Approve Invoice',
       'Credit Memo Creation', 'Fill Credit Memo'], dtype=object)

In [72]:
df2.sort_values(['CaseId','StartTimestamp','EndTimestamp'],inplace=True,ignore_index=True)
df2['counter'] = int(0)
df2.head(15)

,Location,Role,VendorID,InvoiceValue,Resource,StartTimestamp,EndTimestamp,CaseId,ActivityName,counter
0,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-28 15:11:00,2021-07-28 17:09:00,140,Invoice Entry,0
1,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-28 17:09:00,2021-07-28 18:38:00,140,Check Customer Payment,0
2,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-28 17:09:00,2021-07-28 18:38:00,140,Credit Memo Entry,0
3,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-29 11:33:00,2021-07-29 11:33:00,140,Refund Customer,0
4,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-29 17:48:00,2021-07-29 18:17:00,140,Re-issuing the invoice,0
5,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-26 12:19:00,2021-07-26 13:23:00,141,Invoice Entry,0
6,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-26 13:35:00,2021-07-26 14:33:00,141,Confirm Payment Received,0
7,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-26 14:28:00,2021-07-26 16:20:00,141,Refund With Special Voucher,0
8,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-26 17:35:00,2021-07-26 18:21:00,141,Complete the Customer Memo,0
9,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-26 17:35:00,2021-07-26 19:33:00,141,Reject Invoice,0
10,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-27 09:33:00,2021-07-27 10:08:00,141,Refund With Standard Voucher,0
11,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-27 10:17:00,2021-07-27 13:47:00,141,Complete the Customer Memo,0
12,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-27 10:35:00,2021-07-27 10:17:00,141,Reject Invoice,0
13,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-27 16:05:00,2021-07-27 19:43:00,141,Refund With Special Voucher,0
14,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-27 16:39:00,2021-07-27 19:43:00,141,Complete the Customer Memo,0

In [76]:
# go through all cases and add counter 1,2,...n for all activities in the order they START
for case_id in df2.CaseId.unique():
    counter = 1
    for index, row in df2.loc[df2['CaseId'] == case_id].sort_values(['StartTimestamp','EndTimestamp']).iterrows():
        df2.iloc[index,9] = int(counter)
        counter += 1

In [77]:
df2.head(15)

,Location,Role,VendorID,InvoiceValue,Resource,StartTimestamp,EndTimestamp,CaseId,ActivityName,counter
0,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-28 15:11:00,2021-07-28 17:09:00,140,Invoice Entry,1
1,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-28 17:09:00,2021-07-28 18:38:00,140,Check Customer Payment,2
2,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-28 17:09:00,2021-07-28 18:38:00,140,Credit Memo Entry,3
3,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-29 11:33:00,2021-07-29 11:33:00,140,Refund Customer,4
4,"Seattle, USA",Invoice Processor,Vendor1,1535.634000,Riley,2021-07-29 17:48:00,2021-07-29 18:17:00,140,Re-issuing the invoice,5
5,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-26 12:19:00,2021-07-26 13:23:00,141,Invoice Entry,1
6,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-26 13:35:00,2021-07-26 14:33:00,141,Confirm Payment Received,2
7,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-26 14:28:00,2021-07-26 16:20:00,141,Refund With Special Voucher,3
8,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-26 17:35:00,2021-07-26 18:21:00,141,Complete the Customer Memo,4
9,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-26 17:35:00,2021-07-26 19:33:00,141,Reject Invoice,5
10,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-27 09:33:00,2021-07-27 10:08:00,141,Refund With Standard Voucher,6
11,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-27 10:17:00,2021-07-27 13:47:00,141,Complete the Customer Memo,7
12,"Seattle, USA",Invoice Processor,Vendor2,1861.381429,Riley,2021-07-27 10:35:00,2021-07-27 10:17:00,141,Reject Invoice,8
13,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-27 16:05:00,2021-07-27 19:43:00,141,Refund With Special Voucher,9
14,"Seattle, USA",Invoice Approver,Vendor2,1861.381429,Addison,2021-07-27 16:39:00,2021-07-27 19:43:00,141,Complete the Customer Memo,10

In [88]:
pd.set_option('display.max_rows', 500)

In [98]:
# shows how many times is certain activity n-th in the order for the dame case id.
# e.g. invoce entry is often first (464 times out of 500)
df2_act = df2.groupby(['ActivityName','counter'])['ActivityName'].aggregate('count')
df2_act = pd.DataFrame(df2_act)
df2_act

                                      ActivityName
ActivityName                 counter
Approve Invoice              4                   4
                             5                 145
                             6                   2
                             8                  42
                             9                   1
                             11                 23
                             13                  1
                             14                 10
                             15                  2
                             16                  1
                             17                 13
Check Customer Payment       1                  16
                             2                 217
                             3                  20
                             4                   3
Complete the Customer Memo   2                   1
                             3                   4
                             4                 227
                             5                  10
                             6                   8
                             7                  81
                             8                   6
                             9                   2
                             10                 48
                             12                  3
                             13                 23
                             14                  2
                             15                  2
                             16                 12
                             18                  1
Confirm Payment Received     1                  17
                             2                 204
                             3                  22
                             4                   1
Credit Memo Creation         5                   2
                             6                 142
                             7                   6
                             8                   2
                             9                  40
                             10                  2
                             12                 21
                             13                  2
                             15                  9
                             16                  2
                             18                 12
                             19                  3
                             20                  1
Credit Memo Entry            1                   1
                             2                  22
                             3                 226
                             4                   7
Fill Credit Memo             6                   4
                             7                 135
                             8                  12
                             9                   2
                             10                 34
                             11                  7
                             12                  2
                             13                 18
                             14                  3
                             15                  2
                             16                  8
                             17                  1
                             18                  3
                             19                 12
                             20                  1
Invoice Entry                1                 464
                             2                  32
                             3                   4
Re-issuing the invoice       4                  19
                             5                 237
                             6                   3
                             7                  10
                             8                 138
                             10                  7
                             11                 36
                             13                  3
                             14                 20
                             16                  1
                             17                 11
                             19                  1
                             20                 14
Refund Customer              2                   1
                             3                   9
                             4                 227
                             5                  19
Refund With Special Voucher  1                   1
                             2                  17
                             3                 153
                             4                   3
                             9                  23
Refund With Standard Voucher 1                   1
                             2                   6
                             3                  62
                             5                   8
                             6                  80
                             7                   6
                             8                   4
                             9                  21
                             10                  2
                             11                  1
                             12                 23
                             13                  3
                             15                 12
                             16                  3
                             17                  1
Reject Invoice               4                   9
                             5                  79
                             6                   5
                             7                   6
                             8                  40
                             9                   4
                             11                 26
                             12                  1
                             14                 15
                             17                  1

## Original sample file

In [97]:
df3 = pd.read_csv('sample_data_msft.csv')
df3 = df3.iloc[:,2:]
df3.head(5)

,VendorID,InvoiceValue,Resource,StartTimestamp,EndTimestamp,CaseId,ActivityName
0,Vendor2,729.27,Casey,2022-07-28 09:23:50.502475,2022-07-28 17:59:05.502475,0,Invoice Entry
1,Vendor2,729.27,Casey,2022-07-28 17:59:05.502475,2022-07-29 00:43:19.302475,0,Check Customer Payment
2,Vendor2,729.27,Casey,2022-07-29 09:43:19.302475,2022-07-29 15:04:04.902475,0,Credit Memo Entry
3,Vendor2,729.27,Casey,2022-07-29 15:04:04.902475,2022-07-29 20:49:00.102475,0,Refund Customer
4,Vendor2,729.27,Casey,2022-08-01 09:49:00.102475,2022-08-01 18:08:30.702475,0,Re-issuing the invoice

In [106]:
len(df3.CaseId.unique())

133

In [101]:
df3.sort_values(['CaseId','StartTimestamp','EndTimestamp'],inplace=True,ignore_index=True)
df3['counter'] = int(0)
df3.head()

,VendorID,InvoiceValue,Resource,StartTimestamp,EndTimestamp,CaseId,ActivityName,counter
0,Vendor2,729.27,Casey,2022-07-28 09:23:50.502475,2022-07-28 17:59:05.502475,0,Invoice Entry,0
1,Vendor2,729.27,Casey,2022-07-28 17:59:05.502475,2022-07-29 00:43:19.302475,0,Check Customer Payment,0
2,Vendor2,729.27,Casey,2022-07-29 09:43:19.302475,2022-07-29 15:04:04.902475,0,Credit Memo Entry,0
3,Vendor2,729.27,Casey,2022-07-29 15:04:04.902475,2022-07-29 20:49:00.102475,0,Refund Customer,0
4,Vendor2,729.27,Casey,2022-08-01 09:49:00.102475,2022-08-01 18:08:30.702475,0,Re-issuing the invoice,0

In [103]:
# go through all cases and add counter 1,2,...n for all activities in the order they START
for case_id in df3.CaseId.unique():
    counter = 1
    for index, row in df3.loc[df3['CaseId'] == case_id].sort_values(['StartTimestamp','EndTimestamp']).iterrows():
        df3.iloc[index,7] = int(counter)
        counter += 1

In [104]:
# shows how many times is certain activity n-th in the order for the dame case id.
df3_act = df3.groupby(['ActivityName','counter'])['ActivityName'].aggregate('count')
df3_act = pd.DataFrame(df3_act)
df3_act

                                      ActivityName
ActivityName                 counter
Approve Invoice              5                  41
                             8                  11
                             11                  6
                             14                  3
                             17                  4
Check Customer Payment       2                  68
Complete the Customer Memo   4                  65
                             7                  24
                             10                 13
                             13                  7
                             16                  4
Confirm Payment Received     2                  65
Credit Memo Creation         6                  41
                             9                  11
                             12                  6
                             15                  3
                             18                  4
Credit Memo Entry            3                  68
Fill Credit Memo             7                  41
                             10                 11
                             13                  6
                             16                  3
                             19                  4
Invoice Entry                1                 133
Re-issuing the invoice       5                  68
                             8                  41
                             11                 11
                             14                  6
                             17                  3
                             20                  4
Refund Customer              4                  68
Refund With Special Voucher  3                   9
                             9                   2
                             12                  1
Refund With Standard Voucher 3                  56
                             6                  24
                             9                  11
                             12                  6
                             15                  4
Reject Invoice               5                  24
                             8                  13
                             11                  7
                             14                  4